require:
  - rubocop-performance
  - rubocop-rails


AllCops:
  Exclude:
    - 'bin/**/*'
    - 'bundle/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/support/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
