require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'db/schema.rb'
    - 'config/environments/*.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Performance/OpenStruct:
  Enabled: true

Rails:
  Enabled: true

Rails/FindBy:
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'db/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
