version: '3.9'

services:
  db:
    image: postgres:14.4
    container_name: trip-app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - trip-app_db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - trip-app_network
    restart: unless-stopped
  
  redis:
    image: redis:7
    container_name: trip-app_redis
    volumes: 
      - trip-app_redis:/data
    ports:
      - '6379:6379'
    networks:
      - trip-app_network
    restart: unless-stopped

volumes:
  trip-app_db:
  trip-app_redis:

networks:
  trip-app_network:
    driver: bridge

