services:
  db:
    image: postgres:16
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file: .env
    tty: true
    stdin_open: true
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT:-8080}:8080

  pghero:
    image: ankane/pghero
    ports:
      - 8085:8080
    environment:
      DATABASE_URL: postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:5432/task-4_development

volumes:
  postgres_data: