version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/dev/postgres
