default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: TripApp_development

test:
  <<: *default
  database: TripApp_test

production:
  <<: *default
  database: TripApp_production
  username: TripApp
  password: <%= ENV["TRIPAPP_DATABASE_PASSWORD"] %>
